class OriginPreferences {
  static const List<String> defaultAlignedCountries = [
    'Switzerland',
    'France',
    'Germany',
    'United States',
    'Japan',
  ];

  static const List<String> allCountries = [
    'Switzerland',
    'France',
    'Germany',
    'United States',
    'Japan',
    'Netherlands',
    'China',
    'Canada',
    'Italy',
    'Spain',
    'United Kingdom',
    'Sweden',
    'Norway',
    'Finland',
    'Albania',
    'Andorra',
    'Armenia',
    'Austria',
    'Azerbaijan',
    'Belarus',
    'Belgium',
    'Bosnia and Herzegovina',
    'Bulgaria',
    'Croatia',
    'Cyprus',
    'Czechia',
    'Denmark',
    'Estonia',
    'Georgia',
    'Greece',
    'Hungary',
    'Iceland',
    'Ireland',
    'Kosovo',
    'Latvia',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Malta',
    'Moldova',
    'Monaco',
    'Montenegro',
    'North Macedonia',
    'Poland',
    'Portugal',
    'Romania',
    'Russia',
    'San Marino',
    'Serbia',
    'Slovakia',
    'Slovenia',
    'Turkey',
    'Ukraine',
    'Vatican City',
  ];

  static String normalize(String text) => text.trim().toLowerCase();
}
